define([], function() {
  return {
    "CommandAddFolders": "Add folders",
    "ButtonGlobalClose": "Close",
    "FolderMenuRetry": "Retry folders Creation",
    "OverflowSuffixFolderStatusSuccess": " (created)",
    "OverflowSuffixFolderStatusFailure": " (not created)",
    "TooltipFolderDelete": "Delete this folder",
    "TooltipFolderStatusSuccess": "Folder created",
    "TooltipFolderStatusProgress": "Folder creation in progress",
    "TooltipFolderStatusFailure": "Folder not created",
    "TooltipOverflowSuffixFoldersToCreate": "additional folders to create",
    "TooltipOverflowSuffixFoldersCreated": "additional folders created",
    "MessageBarTooManyCharacters": "Total URL length too long. Maximum length of the URL: ",
    "MessageBarMaxFoldersBatch": "Maximum folders to create at once: ",
    "LabelCurrentLocation": "Current location:",
    "TextFieldLabel": "Folder name",
    "TextFieldDescription": "Type a folder name then press \"Tab\" or \"Enter\" key",
    "ButtonClearSelection": "Clear selection",
    "ButtonCreateFolders": "Create folders",
    "ToggleSelectFoldersCreationMode": "Nested folders",
    "CalloutBannedCharacters": "Following characters aren't allowed:",
    "CalloutBannedWords": "Following words aren't allowed:",
    "CalloutBannedPrefixCharacters": "Folder's name can't start with",
    "CalloutBannedFormsWordAtRoot": "isn't supported when the folder is at the root level for a library",
    "CalloutBannedAttachmentsWordAtRoot": "isn't supported when the folder is at the root level for a list",
    "CalloutBannedCharactersUrl": "More information:",
    "CalloutBannedCharactersUrlLink": "here"
  }
});
