define([], function() {
  return {
    "CommandAddFolders": "Ajouter des dossiers",
    "ButtonGlobalClose": "Fermer",
    "FolderMenuRetry": "Recréer les dossiers",
    "OverflowSuffixFolderStatusSuccess": " (créé)",
    "OverflowSuffixFolderStatusFailure": " (non créé)",
    "TooltipFolderDelete": "Supprimer ce dossier",
    "TooltipFolderStatusSuccess": "Dossier créé",
    "TooltipFolderStatusProgress": "Dossier en cours de création",
    "TooltipFolderStatusFailure": "Dossier non créé",
    "TooltipOverflowSuffixFoldersToCreate": "dossier(s) supplémentaire(s) à créer",
    "TooltipOverflowSuffixFoldersCreated": "dossier(s) supplémentaire(s) créés",
    "MessageBarTooManyCharacters": "Longueur totale de l'URL atteinte. Nombre de caractères maximum autorisé : ",
    "MessageBarMaxFoldersBatch": "Nombre maximum de dossiers pouvant être créés à la fois : ",
    "LabelCurrentLocation": "Emplacement courant :",
    "TextFieldLabel": "Nom du dossier",
    "TextFieldDescription": "Saisir un nom de dossier puis terminer par \"Tab\" ou \"Entrée\"",
    "ButtonClearSelection": "Effacer la sélection",
    "ButtonCreateFolders": "Créer les dossiers",
    "ToggleSelectFoldersCreationMode": "Ajout hierarchique",
    "CalloutBannedCharacters": "Les caractères suivants sont interdits :",
    "CalloutBannedWords": "Les noms suivants ne sont pas autorisés :",
    "CalloutBannedPrefixCharacters": "Le dossier ne peut commencer par",
    "CalloutBannedFormsWordAtRoot": "n’est pas pris en charge lorsque le dossier se trouve au niveau racine pour une bibliothèque",
    "CalloutBannedAttachmentsWordAtRoot": "n’est pas pris en charge lorsque le dossier se trouve au niveau racine pour une liste",
    "CalloutBannedCharactersUrl": "Plus d'informations :",
    "CalloutBannedCharactersUrlLink": "ici"
  }
});
